export const STOCK_UPDATE_SUCCESS = "STOCK_UPDATE_SUCCESS";
export const STOCK_UPDATE_FAIL = "STOCK_UPDATE_FAIL";
export const STOCK_UPDATE_RESET = "STOCK_UPDATE_RESET";

export const ADD_STOCK_HISTORY = "ADD_STOCK_HISTORY";
export const DELETE_STOCK_HISTORY = "DELETE_STOCK_HISTORY";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
